# Generated by Django 3.1 on 2020-09-01 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='category',
        ),
        migrations.RemoveField(
            model_name='news',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='news',
            name='updated',
        ),
    ]
