# Generated by Django 3.1 on 2020-09-01 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0003_auto_20200901_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='descriptions',
            field=models.TextField(null=True),
        ),
    ]
