# Generated by Django 3.1 on 2020-09-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0006_auto_20200903_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(null=True, upload_to='article'),
        ),
    ]
